### ISSUE TITLE
grammar described in LANGUAGE.md does not match that of examples in llhd-sim repo ?

### ISSUE THREAD

**Issue by gameboo** [fabianschuiki/llhd#123]
Hi,

I am not sure if this belongs here or in an [llhd-sim](https://github.com/fabianschuiki/llhd-sim) issue, but It looks to me like there are inconsistencies between the description of some instructions in [LANGUAGE.md](https://github.com/fabianschuiki/llhd/blob/master/doc/LANGUAGE.md) and examples in [llhd-sim](https://github.com/fabianschuiki/llhd-sim), at least if I look at [four_pulses.llhd](https://github.com/fabianschuiki/llhd-sim/blob/master/tests/four_pulses.llhd).

I presume some new more permissive syntax is implemented in [llhd-sim](https://github.com/fabianschuiki/llhd-sim), and therefore it is the spec in [LANGUAGE.md](https://github.com/fabianschuiki/llhd/blob/master/doc/LANGUAGE.md) that should be updated?

From checking [four_pulses.llhd](https://github.com/fabianschuiki/llhd-sim/blob/master/tests/four_pulses.llhd), [instances.llhd](https://github.com/fabianschuiki/llhd-sim/blob/master/tests/instances.llhd) and [pointer_shl_shr.llhd](https://github.com/fabianschuiki/llhd-sim/blob/master/tests/inst/pointer_shl_shr.llhd) (and not in an exhaustive or systematic manner, so there may be more interesting things?... And possibly some in other examples too?), the things that I bumped into and that didn't seam to comply with the model of the language I had when reading [LANGUAGE.md](https://github.com/fabianschuiki/llhd/blob/master/doc/LANGUAGE.md) are:

- it looks like the `->` is not necessary in the definition of a `proc` or `entity`
- the explicit type seams to be omitted on most instructions
- commas seam to not be required to separate some instruction arguments
- instructions seam to be able to consume literals
- `wait` can have an empty list of observed values
- `drv` can omit the `after ...` clause
- `var` can omit the initializer
- `st` is called `store`
- `ld` is called `load`
- extra typing is provided on a `store` than on a `st`

I might edit this if I find more things that I think might be out of sync.

**Comment by fabianschuiki** [comment]
Thanks for catching this. Indeed, the llhd-sim repository is lagging behind at the moment: it uses LLHD v0.9, and the examples are even more outdated. I'm hoping to get around to updating llhd-sim soon, and adding a more extensive set of simulation tests (including better verification of simulation output).

The currently supported grammar is here: [src/assembly/grammar.lalrpop](https://github.com/fabianschuiki/llhd/blob/master/src/assembly/grammar.lalrpop)

And the grammar I'm trying to converge to is the one from the [paper](https://arxiv.org/abs/2004.03494).

**Comment by gameboo** [comment]
Oh I see.

So basically it is the opposite of what I thought, where the syntax described in [LANGUAGE.md](https://github.com/fabianschuiki/llhd/blob/master/doc/LANGUAGE.md) is effectively closer to "the one true syntax" than the one in [llhd-sim](https://github.com/fabianschuiki/llhd-sim)... (right?)

Are there any sample `*.llhd` files using the syntax from the paper available somewhere?

**Comment by fabianschuiki** [comment]
> So basically it is the opposite of what I thought, where the syntax described in [LANGUAGE.md](https://github.com/fabianschuiki/llhd/blob/master/doc/LANGUAGE.md) is effectively closer to "the one true syntax" than the one in [llhd-sim](https://github.com/fabianschuiki/llhd-sim)... (right?)

Exactly :+1:. It's a bit unfortunate that the simulator lags behind a bit, but I haven't yet found a good solution how to drive forward the assembly/API without some slack on simulator updates.

> Are there any sample `*.llhd` files using the syntax from the paper available somewhere?

Not completely. The most up-to-date are the [llhd tests](https://github.com/fabianschuiki/llhd/tree/master/test), as well as those [tests in the moore compiler](https://github.com/fabianschuiki/moore/tree/master/test/svlog) that verify some of the generated IR. 

I hope to get around to updating things soon. In the meantime, feel free to hack away at the `grammar.lalrpop` or the `LANGUAGE.md` file in this repository :smiley:!

**Comment by gameboo** [comment]
More lockdown, so more of me reading through this...

I am trying to wrap my head around the rules to parse a basic block by inferring from the codes snippets I find in the paper, in various example files, and in `LANGUAGE.md` (on the one hand I am unfamiliar with rust, and on the other, I am also keen to be able to understand the grammar from the documentation rather than from the code).

I think there is something ambiguous (maybe contradictory?) regarding basic block labels. In https://github.com/fabianschuiki/llhd/blob/master/doc/LANGUAGE.md#names we see that names should always start with `@` or `%`.
In https://github.com/fabianschuiki/llhd/blob/master/doc/LANGUAGE.md#basic-blocks, we can see what is most likely a typo regarding a basic block's syntax: `%<bb_name>:`. At this point in the document, I haven't seen anything defining `<bb_name>` yet (I think...) so I am assuming it is just a name as previously defined. Beyond the fact that it may be just a typo which would technically parse things like `%@foo` or `%%bar`, a few questions are raised in my mind: is it intended that a basic block names is only ever a local name starting with `%` (which presumably is a reasonable thing...)? In `llhd/test/block_labels.llhd`  for example, or even the paper, I can see a "new" form of name ("new" as in "not part of the name formats described in `LANGUAGE.md`"), which is not preceded by either a `@` or a `%` when defining a basic block. I also see that those names are used as target basic blocks but this time starting with a `%`.

What would be the "one true" definition for what should be valid llhd here?

**Comment by fabianschuiki** [comment]
That's an excellent catch. And you're right, it's a typo in the [basic blocks section](https://github.com/fabianschuiki/llhd/blob/master/doc/LANGUAGE.md#basic-blocks). That should read as `<bb_name>:`, where `<bb_name>` must match `[a-zA-Z0-9_\.\\]+`. Are you up for fixing the documentation and possibly any tests where the old style is still present?

**Comment by gameboo** [comment]
I opened #149 which should fix this and clarify what I wasn't understanding. Hopefully it is accurate?

(The thing that threw me off a bit was that referring to a basic block in `phi` / `br` / `wait` still use the `%` form of the name, so I made it explicit that this was how things should be)

**Comment by fabianschuiki** [comment]
Yeah that's, perfect, thansk a lot. Just merged that PR. Do you see any other discrepancies between `LANGUAGE.md` and the paper/llhd-sim repo? Otherwise let's close this issue and open new ones for discrepancies as they arise!

**Comment by gameboo** [comment]
@fabianschuiki Apologies I never got back to you. I haven't gotten around to check for other potential discrepancies, sorry... But by all means close this issue, I can still search the closed issues if I ever manage to get back to it and need to remind myself of what was going on.

Happy 2021 ;)

**Comment by fabianschuiki** [comment]
@gameboo No worries, and thanks for the effort. Happy 2021 to you too :smiley:
